# Generated by Django 4.1 on 2024-02-08 09:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ready_to_publish', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('publish', 'publish'), ('decline', 'decline'), ('hold', 'hold'), ('contract', 'contract')], max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('adddress', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('county', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=10)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('content', models.TextField(default='')),
                ('video_link', models.URLField()),
                ('main_image', models.FileField(blank=True, null=True, upload_to='media/properties')),
                ('pub_date', models.DateField(default=datetime.datetime(2024, 2, 8, 9, 25, 53, 704323))),
                ('feature', models.ManyToManyField(blank=True, null=True, to='listings.featuremaster')),
            ],
        ),
        migrations.CreateModel(
            name='TypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='media/properties')),
                ('property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.properties')),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, to='listings.typemaster'),
        ),
        migrations.AddField(
            model_name='properties',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
