# Generated by Django 4.1 on 2024-02-08 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 10, 43, 17, 225965)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='status',
            field=models.CharField(blank=True, choices=[('publish', 'publish'), ('decline', 'decline'), ('hold', 'hold'), ('contract', 'contract')], max_length=10),
        ),
    ]
