# Generated by Django 4.1 on 2024-02-12 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_properties_pub_date_alter_properties_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 12, 7, 59, 41, 261522)),
        ),
    ]
