# Generated by Django 4.1 on 2024-02-12 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_properties_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='area_unit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='buildup_area',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='buildup_area_unit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='carpet_area',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='carpet_area_unit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 12, 8, 4, 31, 569958)),
        ),
    ]
