# Generated by Django 4.1 on 2024-02-18 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_properties_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 7, 5, 42, 192992)),
        ),
    ]
