# Generated by Django 4.0.3 on 2024-03-14 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_properties_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 14, 16, 36, 55, 597705)),
        ),
    ]
