# Generated by Django 4.0.3 on 2024-03-14 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_properties_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='expire_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 14, 16, 9, 31, 331668)),
        ),
    ]
