# Generated by Django 4.0.3 on 2024-03-24 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_properties_bathroom_properties_bedroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 24, 7, 54, 11, 993944)),
        ),
    ]
